name: my_expenses
description: An app that helps you to keep track of your expenses.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.4+74

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  csv: ^6.0.0
  darq: ^2.1.0
  device_info_plus: ^12.1.0
  drift: ^2.28.1
  drift_flutter: ^0.2.6
  enum_to_string: ^2.2.1
  extension_google_sign_in_as_googleapis_auth: ^2.0.13
  fl_chart: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_colorpicker: ^1.1.0
  flutter_local_notifications: ^19.4.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_timezone: ^4.1.1
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.10.0
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  google_sign_in: ^6.3.0
  googleapis: ^14.0.0
  image_picker: ^1.2.0
  internet_connection_checker_plus: ^2.8.0
  json_annotation: ^4.9.0
  local_auth: ^2.3.0
  logger: ^2.6.1
  month_picker_dialog: ^6.5.0
  open_filex: ^4.7.0
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  photo_view: ^0.15.0
  rate_my_app: ^2.3.2
  responsive_builder: ^0.7.1
  shared_preferences: ^2.5.3
  sprintf: ^7.0.0
  steel_crypt: ^3.0.0+1
  transparent_image: ^2.0.1
  url_launcher: ^6.3.2
  version_tracker:
    git:
      url: https://github.com/Wolfteam/version_tracker.git
  workmanager: ^0.6.0

dev_dependencies:
  build_runner:
  drift_dev: ^2.28.2
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  intl_utils: ^2.8.10
  json_serializable: ^6.9.5
  lint: ^2.8.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/cost.png"
  image_path_ios: "assets/images/cost_ios.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/cost.png
    - assets/fonts/OpenSans-Regular.ttf
    - assets/fonts/OpenSans-Bold.ttf
    - assets/fonts/OpenSans-Italic.ttf
    - assets/fonts/OpenSans-BoldItalic.ttf
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

flutter_intl:
  enabled: true
